-- AlterTable
ALTER TABLE "Customer" ADD COLUMN     "gstin" TEXT,
ADD COLUMN     "state" TEXT;

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "cgst" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "customerGstin" TEXT,
ADD COLUMN     "gstType" TEXT NOT NULL DEFAULT 'CGST_SGST',
ADD COLUMN     "igst" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "notes" TEXT,
ADD COLUMN     "placeOfSupply" TEXT,
ADD COLUMN     "sgst" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxableAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalGst" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "gstRate" DOUBLE PRECISION NOT NULL DEFAULT 18,
ADD COLUMN     "hsnCode" TEXT;

-- AlterTable
ALTER TABLE "Plan" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "state" TEXT;
